from ..esra.transformers.entity_type_splitter import entity_type_split

def test_entity_type_split():
    data_in = {'entities': [['OtherScientificTerm', 'black-box nature'],
                            ['Method', 'deep learning models'], 
                            ['Generic', 'methods'],
                            ['Generic', 'models'],
                            ['Method', 'model-agnostic and model-specific explanation methods'],
                            ['Method', 'CNNs'],
                            ['Task', 'text classification'],
                            ['Task', 'human-grounded evaluations'],
                            ['OtherScientificTerm', 'model behavior'],
                            ['Method', 'model predictions'],
                            ['Method', 'explanation methods'],
                            ['Generic', 'methods']],
                'relations':[['USED-FOR', 1, 2],
                            ['USED-FOR', 2, 3],
                            ['USED-FOR', 4, 7],
                            ['USED-FOR', 5, 8]]
                }

    data_out = {'entities': ['black-box nature',
                            'deep learning models',
                            'methods',
                            'models',
                            'model-agnostic and model-specific explanation methods',
                            'CNNs',
                            'text classification',
                            'human-grounded evaluations',
                            'model behavior',
                            'model predictions',
                            'explanation methods',
                            'methods',
                            'OtherScientificTerm',
                            'Method',
                            'Generic',
                            'Task'],
                'relations': [['USED-FOR', 1, 2],
                            ['USED-FOR', 2, 3],
                            ['USED-FOR', 4, 7],
                            ['USED-FOR', 5, 8],
                            ['IS-A', 0, 12],
                            ['IS-A', 1, 13],
                            ['IS-A', 2, 14],
                            ['IS-A', 3, 14],
                            ['IS-A', 4, 13],
                            ['IS-A', 5, 13],
                            ['IS-A', 6, 15],
                            ['IS-A', 7, 15],
                            ['IS-A', 8, 12],
                            ['IS-A', 9, 13],
                            ['IS-A', 10, 13],
                            ['IS-A', 11, 14]]}

    assert data_out == entity_type_split(data_in)